# Generated by Django 5.2.5 on 2025-08-14 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogpost',
            new_name='blogspost',
        ),
    ]
